# Generated by Django 3.1.3 on 2022-04-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleTodoList',
        ),
    ]
